apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-application-servers
  namespace: frontends
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-frontends-wordpress-application-servers
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
     labels:
        workload.user.cattle.io/workloadselector: deployment-frontends-wordpress-application-servers
    spec:
      containers:
      - env:
        - name: WORDPRESS_DEBUG:
          value: 1
        - name: WORDPRESS_AUTH_KEY
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_AUTH_KEY
              name: wordpressvariables
              optional: false
        - name: WORDPRESS_AUTH_SALT
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_AUTH_SALT
              name: wordpressvariables
              optional: false
        - name: WORDPRESS_LOGGED_IN_KEY
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_LOGGED_IN_KEY
              name: wordpressvariables
              optional: false
        - name: WORDPRESS_NONCE_SALT
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_NONCE_SALT
              name: wordpressvariables
              optional: false
        - name: WORDPRESS_SECURE_AUTH_KEY
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_SECURE_AUTH_KEY
              name: wordpressvariables
              optional: false
        - name: WORDPRESS_SECURE_AUTH_SALT
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_SECURE_AUTH_SALT
              name: wordpressvariables
              optional: false
        - name: WORDPRESS_NONCE_KEY
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_NONCE_KEY
              name: wordpressvariables
              optional: false
        - name: WORDPRESS_DB_HOST_WRITER
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_HOST_WRITER
              name: wordpressvariables
              optional: false
        - name: WORDPRESS_DB_HOST_READER
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_HOST_READER
              name: wordpressvariables
              optional: false
        - name: HA_WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_NAME
              name: wordpressvariables
              optional: false
        - name: HA_WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_PASSWORD
              name: wordpressvariables
              optional: false
        - name: HA_WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_USER
              name: wordpressvariables
              optional: false
        - name: WORDPRESS_REDIS_HOST_MASTER
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_REDIS_HOST_MASTER
              name: wordpressvariables
              optional: false
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_NAME
              name: wordpressvariables
              optional: false
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_PASSWORD
              name: wordpressvariables
              optional: false
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_USER
              name: wordpressvariables
              optional: false
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_HOST_WRITER
              name: wordpressvariables
        image: amazecom/hyperwordpress:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        name: wordpress-application-servers
        ports:
        - containerPort: 80
          name: 80tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/www/html/wp-content/plugins/
          name: plugins
          subPath: wordpress-plugins
        - mountPath: /var/www/html/wp-content/themes/
          name: themes
          subPath: wordpress-themes
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: plugins
        persistentVolumeClaim:
          claimName: wordpressplugins
      - name: themes
        persistentVolumeClaim:
          claimName: wordpressthemes
