ind: Service
apiVersion: v1
metadata:
  name: wordpress-application-servers
spec:
  selector:
    app: wordpress-application-servers
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-wordpress-application-servers
  labels:
    app: wordpress-application-servers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-application-servers
  template:
    metadata:
      labels:
        app: helloserver
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: wordpress-application-servers
        image: amazecom/hyperwordpress:latest
        ports:
        - containerPort: 80
